### PR TITLE
Set target java version to 1.8

### LINKED ISSUE #40: 0.1.15: Incomaptible with Java 8
Build fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'sg-ff2-parent'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.psxpaul:gradle-execfork-plugin:0.1.15.
     Required by:
         project : > com.github.psxpaul.execfork:com.github.psxpaul.execfork.gradle.plugin:0.1.15
      > No matching variant of com.github.psxpaul:gradle-execfork-plugin:0.1.15 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.0' but:
          - Variant 'apiElements' capability com.github.psxpaul:gradle-execfork-plugin:0.1.15 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0')
          - Variant 'runtimeElements' capability com.github.psxpaul:gradle-execfork-plugin:0.1.15 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0')
```

Might be an issue similiar to https://github.com/JetBrains/markdown/issues/70 ?

### PR DESCRIPTION
**Pull request by CliveEvans**
Fixes #40

### CODE REVIEW

**Comment by CliveEvans** [comment]
@psxpaul any chance you could look at this?

We're currently stuck in the hard place between not upgrading gradle, finding another plugin that will do this for us and you accepting this pull request. We'd really like to upgrade gradle, and we'd rather not look for a new plugin, we like this one. (Sadly swapping to a newer java version isn't possible, our target is old hardware that won't run a newer jvm)

**Comment by cwebbtw** [comment]
@psxpaul is there any opportunity to get this merged?

**Comment by jcraya** [comment]
@psxpaul would it be possible to release a new version with this fix merged? Thank you!

**Comment by bnasslahsen** [comment]
@psxpaul, 

Could you please release the new version that supports Java 8 ?

**Pull request merged**
