### PR TITLE
Fixes #45

### LINKED ISSUE #45: Incompatible with Gradle configuration cache
The plugin cannot be used in a project that also uses the new configuration cache (https://docs.gradle.org/7.2/userguide/configuration_cache.html)

When trying to enable the config cache there is a build failure and this message:

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

```
- Plugin 'com.github.psxpaul.execfork': registration of listener on 'Gradle.addBuildListener' is unsupported
  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners
```

### PR DESCRIPTION
**Pull request by DreierF**
Hi @psxpaul,

This PR implements support for the Gradle configuration cache.
There were two issues with the current implementation that made it incompatible:
- The usage of `gradle.addBuildListener` to determine when the build finished as this is not cacheable. As [suggested by the Gradle docs](https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners) I replaced this with a build service that implements `OperationCompletionListener` to determine when the build finishes.
- The usage of `project` during the execution phase

To avoid issues with configuration avoidance I also moved the creation of the join tasks to the stopAfter action. This means the task will no longer be created if the exec fork task does not use the `stopAfter` option which also means we no longer need to eagerly create the exec tasks.

Would be great if you could have a look at it :)

### CODE REVIEW

**Comment by DreierF** [comment]
@psxpaul I resolved the merge conflicts with master

**Comment by DreierF** [comment]
BTW this can be tested by running the sample projects with `--configuration-cache`. It works for all projects but the spring boot one, because the spring boot plugin itself is not yet compatible with the configuration cache. Unfortunately there is no API yet to enable the configuration cache programmatically for the `GradleBuild` task ([Gradle Issue](https://github.com/gradle/gradle/issues/14375))

**Comment by psxpaul** [comment]
@DreierF this appears to have broken the build, so I'm unable to release these changes. Can you take a look at ExecForkPluginTest?

**Comment by DreierF** [comment]
Sure, I'll take a look

**Comment by DreierF** [comment]
I fixed the test in https://github.com/psxpaul/gradle-execfork-plugin/pull/50 but for some reason ./gradlew test still causes test failure that I don't really understand, but might as be an issue with my local setup

**Pull request merged**
